name: Run Tests

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.6.0"
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test